project:
  type: book
  output-dir: docs

book:
  title: "spatial_data_science"
  author: "Julia Cardwell"
  date: "10/7/2025"
  chapters:
    - index.qmd
    - syllabus.qmd
    - schedule.qmd
    - competencies.qmd
    - labs.qmd
    - other_files.qmd
    - introduction_to_R.qmd
    - tidyverse_basics.qmd
    - tidyverse.qmd
    - describing_spatial_data.qmd
    - wrangling.qmd
    - spatial_wrangling.qmd
    - analytical_datasets.qmd
    - tmap.qmd
    - ppa.qmd
    - autocorrelation.qmd
    - exploring_two.qmd
	


format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

